spacy_doc_in_json_format = {
    "id": "b5d070ef-056e-43bf-a902-70f069ab9939",
    "genre": "quote",
    "author": "Mussum",
    "text": "Minhi vidis é um livris abertis.",
    "ents": [{"start": 0, "end": 5, "label": "LOC"}],
    "sents": [{"start": 0, "end": 32}],
    "tokens": [
        {
            "id": 0,
            "start": 0,
            "end": 5,
            "tag": "PROPN",
            "pos": "PROPN",
            "morph": "Gender=Masc|Number=Sing",
            "lemma": "Minhi",
            "dep": "nsubj",
            "head": 4,
        },
        {
            "id": 1,
            "start": 6,
            "end": 11,
            "tag": "NOUN",
            "pos": "NOUN",
            "morph": "Gender=Masc|Number=Plur",
            "lemma": "vidis",
            "dep": "flat:name",
            "head": 0,
        },
        {
            "id": 2,
            "start": 12,
            "end": 13,
            "tag": "AUX",
            "pos": "AUX",
            "morph": "Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin",
            "lemma": "ser",
            "dep": "cop",
            "head": 4,
        },
        {
            "id": 3,
            "start": 14,
            "end": 16,
            "tag": "DET",
            "pos": "DET",
            "morph": "Definite=Ind|Gender=Masc|Number=Sing|PronType=Art",
            "lemma": "um",
            "dep": "det",
            "head": 4,
        },
        {
            "id": 4,
            "start": 17,
            "end": 23,
            "tag": "NOUN",
            "pos": "NOUN",
            "morph": "Gender=Masc|Number=Plur",
            "lemma": "livris",
            "dep": "ROOT",
            "head": 4,
        },
        {
            "id": 5,
            "start": 24,
            "end": 31,
            "tag": "ADJ",
            "pos": "ADJ",
            "morph": "Gender=Fem|Number=Sing",
            "lemma": "abertis",
            "dep": "amod",
            "head": 4,
        },
        {
            "id": 6,
            "start": 31,
            "end": 32,
            "tag": "PUNCT",
            "pos": "PUNCT",
            "morph": "",
            "lemma": ".",
            "dep": "punct",
            "head": 4,
        },
    ],
}
